const frozenBlocks = [
  { validator: "Shido Three", missedBlocks: 22090 },
  { validator: "Shido Two", missedBlocks: 21663 },
  { validator: "NeoNode", missedBlocks: 19860 },
  { validator: "🔥DefiMike🔥Restake🔥", missedBlocks: 17711 },
  { validator: "Shido Five", missedBlocks: 16879 },
  { validator: "Shido Australia Co. | Restake", missedBlocks: 13162 },
  { validator: "🔥 SHIDOFORGE ⚒ 🔥 REStake", missedBlocks: 13148 },
  { validator: "🚀 WHEN MOON 🌕 WHEN LAMBO 🔥 RESTAKE ✅", missedBlocks: 12403 },
  { validator: "🇫🇷 ShidoFrance One 🇫🇷", missedBlocks: 12257 },
  { validator: "Scafire Node 5% Fee REStake Fast ❤️", missedBlocks: 12052 },
  { validator: "SHIDO4LIFE 🥋🤺👊🏼 | ✅ REStake", missedBlocks: 11887 },
  { validator: "Olim 🥷 VIP Services RESTAKE", missedBlocks: 11309 },
  { validator: "🟢 Shidoverse  🔥  REStake  🚀", missedBlocks: 10851 },
  { validator: "ShidoGuard", missedBlocks: 8593 },
  { validator: "CryptoWav3z", missedBlocks: 8364 },
  { validator: "BG-SHI-VAL01🦁 | REStake", missedBlocks: 7960 },
  { validator: "Indonode | Restake", missedBlocks: 6563 },
  { validator: "Shido Seven", missedBlocks: 5914 },
  { validator: "ChainTools", missedBlocks: 4844 },
  { validator: "Blue Trust 🤝", missedBlocks: 4280 },
  { validator: "🇳🇱ShidoDutch🇳🇱 |REStake", missedBlocks: 3718 },
  { validator: "ShidoObserver || REStake", missedBlocks: 3713 },
  { validator: "🇸🇪 In Bjorn We Trust", missedBlocks: 3197 },
  { validator: "Shido Six", missedBlocks: 3125 },
  { validator: "FrankLinvest📈 | RESTAKE☆", missedBlocks: 3112 },
  { validator: "KENSEI ⚔️", missedBlocks: 3041 },
  { validator: "Maverick | MavNode - REStake", missedBlocks: 1389 },
  { validator: "Fox Node🦊 | RESTAKE", missedBlocks: 743 },
  { validator: "Blockval | Restake", missedBlocks: 463 },
  { validator: "Superbit123 & DAOverse | REStake~", missedBlocks: 276 },
  { validator: "JquickDeFi", missedBlocks: 148 },
  { validator: "256x25 /reStake", missedBlocks: 145 },
  { validator: "MetaDefi || RESTAKE", missedBlocks: 86 },
  { validator: "Nuke Node | RESTAKE", missedBlocks: 0 },
  { validator: "xshrimp", missedBlocks: 0 },
  { validator: "MagicShidoNode 🧙‍♂️🔮🌟🪄 | ✅ REStake", missedBlocks: 0 },
  { validator: "Shido Four", missedBlocks: 0 },
  { validator: "Neev Labs", missedBlocks: 0 }
];
